# Generated by Django 5.1.1 on 2024-09-25 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_menuitemsize"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menuitem",
            name="price",
        ),
    ]
