# Generated by Django 5.1.1 on 2024-09-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_remove_coffeeshop_opening_hours_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coffeeshop",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=9, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="coffeeshop",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=9, max_digits=9, null=True
            ),
        ),
    ]
