# Generated by Django 5.1.1 on 2024-09-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_coffeeshop_latitude_alter_coffeeshop_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coffeeshop",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=9, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="coffeeshop",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=9, max_digits=12, null=True
            ),
        ),
    ]
