# Generated by Django 5.1.1 on 2024-09-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_coffeeshop_latitude_alter_coffeeshop_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="favorite_coffee_shops",
            field=models.ManyToManyField(
                blank=True, related_name="favorited_by", to="api.coffeeshop"
            ),
        ),
    ]
