# Generated by Django 5.1.1 on 2024-10-15 10:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_alter_coffeeshopapplication_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="verification_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
