# Generated by Django 5.1.1 on 2024-10-16 13:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_passwordresetattempt"),
    ]

    operations = [
        migrations.CreateModel(
            name="RatingToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "coffee_shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.coffeeshop"
                    ),
                ),
            ],
        ),
    ]
