# Generated by Django 5.1.1 on 2024-10-18 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_coffeeshop_is_under_maintenance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menuitem",
            name="image",
        ),
        migrations.AddField(
            model_name="menuitem",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="MenuItemImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="menu_items/")),
                (
                    "menu_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="api.menuitem",
                    ),
                ),
            ],
        ),
    ]
