# Generated by Django 5.1.1 on 2024-10-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_alter_coffeeshop_latitude_alter_coffeeshop_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coffeeshop",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=15, max_digits=18, null=True
            ),
        ),
        migrations.AlterField(
            model_name="coffeeshop",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=15, max_digits=18, null=True
            ),
        ),
    ]
