# Generated by Django 5.1.1 on 2024-10-21 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_remove_menuitem_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
    ]
