# Generated by Django 5.1.1 on 2024-10-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_menuitem_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="coffeeshop",
            name="is_terminated",
            field=models.BooleanField(default=False),
        ),
    ]
