# Generated by Django 5.1.1 on 2024-10-24 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_coffeeshop_is_terminated"),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuItemImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="menu_items/additional/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "menu_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additional_images",
                        to="api.menuitem",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
