# Generated by Django 5.1.1 on 2024-10-26 15:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0026_contactinformation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactinformation",
            name="primary_phone",
            field=models.CharField(
                blank=True,
                max_length=17,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be 9-15 digits. Can optionally start with '+'.",
                        regex="^(?:\\+)?(?:1)?\\d{9,15}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="contactinformation",
            name="secondary_phone",
            field=models.CharField(
                blank=True,
                max_length=17,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be 9-15 digits. Can optionally start with '+'.",
                        regex="^(?:\\+)?(?:1)?\\d{9,15}$",
                    )
                ],
            ),
        ),
    ]
