# Generated by Django 5.1.1 on 2024-10-30 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0028_emailchangecode_usernamechangecode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usernamechangecode",
            name="user",
        ),
        migrations.DeleteModel(
            name="EmailChangeCode",
        ),
        migrations.DeleteModel(
            name="UsernameChangeCode",
        ),
    ]
