# Generated by Django 5.1.1 on 2024-11-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0031_delete_emailverificationcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="coffeeshop",
            name="dti_permit",
            field=models.FileField(blank=True, null=True, upload_to="dti_permits/"),
        ),
    ]
