# Generated by Django 5.1.1 on 2024-11-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0032_coffeeshop_dti_permit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
