# Generated by Django 5.1.1 on 2024-11-26 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0034_promo_has_specific_schedule_promoschedule"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="promo",
            name="has_specific_schedule",
        ),
        migrations.DeleteModel(
            name="PromoSchedule",
        ),
    ]
