# Generated by Django 5.1.1 on 2024-11-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0035_remove_promo_has_specific_schedule_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="promo",
            name="days",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="promo",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="promo",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
