# Generated by Django 5.1.1 on 2024-11-28 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0036_promo_days_promo_end_time_promo_start_time"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="rating",
            unique_together=set(),
        ),
    ]
